export const LABELS = {
  "olhos_abertos": "Olhos abertos",
  "olhos_fechados": "Olhos fechados",
  "olho_esquerdo_fechado": "Olho esquerdo fechado",
  "olho_direito_fechado": "Olho direito fechado",
  "piscando": "Possível piscada em curso",
  "piscou": "Piscada observada",
  "olhos_semicerrados": "Olhos semicerrados",
  "olhos_arregalados": "Olhos arregalados",
  "boca_aberta": "Boca aberta",
  "boca_fechada": "Boca fechada",
  "boca_muito_aberta": "Boca muito aberta",
  "labios_franzidos": "Lábios franzidos",
  "labios_projetados": "Lábios projetados",
  "labios_pressionados": "Lábios pressionados",
  "sorrindo": "Sorrindo",
  "sorriso_leve": "Sorriso leve",
  "sorriso_assimetrico": "Sorriso assimétrico",
  "sobrancelhas_elevadas": "Sobrancelhas elevadas",
  "sobrancelhas_franzidas": "Sobrancelhas franzidas",
  "sobrancelha_esquerda_elevada": "Sobrancelha esquerda elevada",
  "sobrancelha_direita_elevada": "Sobrancelha direita elevada",
  "nariz_franzido": "Nariz franzido",
  "bochechas_infladas": "Bochechas infladas",
  "mandibula_esquerda": "Mandíbula deslocada à esquerda",
  "mandibula_direita": "Mandíbula deslocada à direita",
  "olhar_lateral": "Olhar lateral",
  "olhar_acima": "Olhar acima",
  "olhar_abaixo": "Olhar abaixo",
  "cabeca_girada": "Cabeça girada",
  "cabeca_inclinada": "Cabeça inclinada",
  "cabeca_frontal": "Cabeça frontal",
  "fechamento_prolongado": "Fechamento ocular prolongado",
  "possivel_bocejo": "Possível bocejo",
  "possivel_sono": "Possível sono",
  "possivel_sonolencia": "Possível sonolência",
  "vigilia_aparente": "Vigília aparente",
  "surpresa_aparente": "Expressão compatível com surpresa",
  "tensao_aparente": "Expressão compatível com tensão",
  "tristeza_aparente": "Possível expressão de tristeza",
  "raiva_aparente": "Possível expressão de raiva",
  "irritacao_aparente": "Expressão compatível com irritação",
  "preocupacao_aparente": "Expressão compatível com preocupação",
  "desconforto_aparente": "Possível desconforto facial",
  "atencao_aparente": "Atenção aparente",
  "neutra": "Expressão neutra",
  "relaxada_aparente": "Expressão facial relaxada"
};
